### PR TITLE
jruby: Try to use JDK version of Xalan

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

See https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-qwq9-89rg-ww72 for documentation on a vulnerability in Xalan, and a note that upstream Xalan is no longer maintained.

See https://github.com/sparklemotion/nokogiri/issues/1829 for a conversation about alternatives to Xalan

This PR attempts to use the JDK's vendored version of Xalan, with only limited success ...

**The Good**

On a positive note, the majority of the changes are simply updating the package paths.

**The Bad**

However, I've discovered that OpenJDK pulled in Xalan 2.6.0 (see https://github.com/openjdk/jdk/commit/74f4779) which **predates** the version of Xalan used to implement Nokogiri and so now I'm a little worried about whether JDKs will all have the same API? Over time this detail has emerged in issues like https://github.com/sparklemotion/nokogiri/issues/1114 and commits like c5ad35a and 6cf2b6e.

I worked around this assuming OpenJDK's API, but I'm worried about portability.

**The Ugly**

Finally, it looks like the Xalan imported into OpenJDK is incomplete and does not contain the class equivalent for Xalan's `./src/org/apache/xalan/transformer/TransformerImpl.java`. In this PR I've used

```java
import com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl;
```

which is incorrect and results in this compiler error:

```
ext/java/nokogiri/XsltStylesheet.java:188: error: cannot find symbol
    SerializationHandler serializationHandler = transformer.createSerializationHandler(streamResult);
                                                           ^
  symbol:   method createSerializationHandler(StreamResult)
  location: variable transformer of type TransformerImpl
```

`com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl` is the analog for Xalan's `./src/org/apache/xalan/xsltc/trax/TransformerImpl.java` which seems to be a very different class despite similar names. I'm not familiar enough with this library to completely understand how these classes are related, and I need help resolving this issue.

Tagging @headius for assistance!

**Have you included adequate test coverage?**

Existing test coverage should prevent any regressions.

**Does this change affect the behavior of either the C or the Java implementations?**

Ideally there will be no behavioral changes, the test suite should help us stay accountable.

### CODE REVIEW

**Comment by kares** [comment]
took a quick look and here's smt that might unblock this (the **ugly part**): https://github.com/sparklemotion/nokogiri/pull/2644

**Comment by kares** [comment]
for the record, after merging with #2644 I am seeing: **4 failures, 3 errors** (using OpenJDK 11)
... the errors are related to the part changed as part of #2644 (which is likely still be fixable)
```
Error:
Nokogiri::XSLT::Stylesheet#test_transform:
Java::ComSunOrgApacheXmlInternalSerializerUtils::WrappedRuntimeException: The Properties object passed to the SerializerFactory does not have a 'method' property.
    java.xml/com.sun.org.apache.xml.internal.serializer.SerializerFactory.getSerializer(SerializerFactory.java:172)
    nokogiri.XsltStylesheet.serialize(XsltStylesheet.java:188)
    nokogiri.XsltStylesheet$INVOKER$i$1$0$serialize_DBG.call(XsltStylesheet$INVOKER$i$1$0$serialize_DBG.gen)

```

however, on Java 17 the whole thing bumps into accessibility issues due having to open the internals we're trying to use from the JDK:
```
Java::JavaLang::IllegalAccessError: superclass access check failed: class nokogiri.internals.XalanDTMManagerPatch (in unnamed module @0x41d20f06) cannot access class com.sun.org.apache.xml.internal.dtm.ref.DTMManagerDefault (in module java.xml) because module java.xml does not export com.sun.org.apache.xml.internal.dtm.ref to unnamed module @0x41d20f06
    java.base/java.lang.ClassLoader.defineClass1(Native Method)
    java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
    java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
    java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
    java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    nokogiri.XmlXpathContext.<clinit>(XmlXpathContext.java:51)
    nokogiri.XmlXpathContext$INVOKER$s$1$0$rbNew_DBG.call(XmlXpathContext$INVOKER$s$1$0$rbNew_DBG.gen)

```
all in all the change to the internal xalan would need more work but at the same time I am not sure it's worth the effort, given the reliance on internals, which the JDK does not want us doing (also makes the change a breaking change to existing users - they would need to adjust JRUBY_OPTS flags to get it working).

**Comment by flavorjones** [comment]
I just pushed the merged version (rebased onto #2644 which I just merged) but I hear and understand what you're saying about using the internals. We can take this knowledge back to #1829 and continue the conversation about alternatives to Xalan.

**Comment by flavorjones** [comment]
Just a reminder: don't delete this branch, it might be useful to refer back to in the future.
