### ISSUE TITLE
undefined method `traverse'

### ISSUE THREAD

**Issue by mperham** [sparklemotion/nokogiri#283]
Seeing this when upgrading from 1.4.1 to 1.4.2:

```
04:53:37.481200 2104 page.rb:158: undefined method `traverse' for 30912:Fixnum
04:53:37.481252 2104 page.rb:159: /home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `block in traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:214:in `block in each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `upto'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `block in traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:214:in `block in each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `upto'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `block in traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:214:in `block in each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `upto'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node_set.rb:213:in `each'
/home/onespot/.bundle/ruby/1.9.1/gems/nokogiri-1.4.2/lib/nokogiri/xml/node.rb:592:in `traverse'
/home/onespot/.bundle/ruby/1.9.1/gems/sanitize-1.2.1/lib/sanitize.rb:129:in `clean_node!'
/home/onespot/.bundle/ruby/1.9.1/gems/sanitize-1.2.1/lib/sanitize.rb:105:in `clean!'
```
