### ISSUE TITLE
Random segmentation faults with Rails

### ISSUE THREAD

**Issue by Xac** [sparklemotion/nokogiri#1452]
I recently updated my Rails application from Rails 3 to Rails 4 and updated Ruby from 1.9 to 2.3. (I later tried 2.2 and 2.1 with the same results).  This issue only happens with Nokogiri 1.6.x (tried 1.6.0-1.6.7), 1.5.x does not have this issue.

I'm using Passenger with NGINX. The application runs fine for the most part, but, once every 10 or so requests, was randomly returning this message to the browser:

Incomplete response received from application
The NGINX logs showed the following:

```
[Client 2-623] Sending 502 response: application did not send a complete response
28741/7f94e2312700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 2521, application /home/admin/apps/<myapp>/current/public
App 2059 stderr: request_handler/thread_handler.rb:226 ]: *** Passenger RequestHandler warning: someone tried to connect with an invalid connect password.
stderr: /home/admin/apps/<myapp>/shared/bundle/ruby/2.2.0/gems/builder-3.2.2/lib/builder/xchar.rb:146:
stderr: [BUG]
stderr: Segmentation fault at 0x00000000000000

```
After some debugging, I found that the issue seemed to be a `strip_tags` call within my view, and removing it stopped the issue. I assume the segmentation fault has something to do with Nokogiri since Rails sanitization is done by Nokogiri in Rails 4.

This issue is very hard to debug because helper.strip_tags seems to work fine in the console, yet it is causing these issues in the view.

I tried the following to fix the issue with no success:

- Make sure libxml2 and all related Nokogiri libraries are installed and up-to-date
- Build Nokogiri with and without `--use-system-libraries`, with and without specifying specific library locations, same issue with any config.
- Build with Nokogiri 1.6.0 and 1.6.7. Neither works, although an additional Rails mailer segfault seems to appear when using 1.6.7.
- Built on Ruby 2.1, 2.2, 2.3 using RVM. All have the same issue.
- Rails 4 secrets.yml is set up correctly with the secret_key_base key.

With strip_tags included, I also get the following Rails application errors randomly. Sometimes the page loads fine, sometimes these errors are triggered:

```
RuntimeError: rehash occurred during iteration
<my controller>#index
[GEM_ROOT]/gems/nokogiri-1.6.0/lib/nokogiri/xml/document.rb, line 210

NoMethodError: undefined method `empty?' for false:FalseClass
<my controller>#index
[GEM_ROOT]/gems/haml-4.0.7/lib/haml/compiler.rb, line 193

```

**Comment by flavorjones** [comment]
Hi,

Thanks for raising this issue. Can you help me reproduce what you're seeing? Do you have a minimal example (or any example) that I can run and see the problem?

**Comment by flavorjones** [comment]
Closing, as no further information was provided.
