### ISSUE TITLE
Error using nokogiri v:1.4.2

### ISSUE THREAD

**Issue by ikvarma** [sparklemotion/nokogiri#320]
Hi 
I came across the following error when i upgraded nokogiri from 1.4.1 to 1.4.2. It says
#### 

dyld: NSLinkModule() error
dyld: Symbol not found: _xmlFirstElementChild
  Referenced from: /Users/nbkjurl/.gem/ruby/1.8/gems/nokogiri-1.4.2/lib/nokogiri/nokogiri.bundle
  Expected in: flat namespace
#### 

when i unistalled 1.4.2 it is working fine
FYI: I am using libxml v: 1.1.4
