### ISSUE TITLE
nokogiri 1.5.0 doesn't work with rubinius 1.2.3

### ISSUE THREAD

**Issue by jeremyevans** [sparklemotion/nokogiri#483]
```
nokogiri.c:41: error: static declaration of 'ruby_strdup' follows non-static declaration
/usr/local/lib/rubinius/include/ruby.h:1736: error: previous declaration of 'ruby_strdup' was here
```

IMO, this is a bug in nokogiri, but evanphx is going to commit a patch so that nokogiri 1.5.0 works in rubinius 1.2.4.  Still, I think it would be nice to issue a 1.5.1 release that works with rubinius 1.2.3 (and possibly older versions of rubinius).
